spring:
  datasource:
    url: jdbc:postgresql://localhost/listicle
    username: listicle
    password: vbfgrt45
    driverClassName: org.postgresql.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC